name: LaTeX Build
on: 
  pull_request:
    branches:
      - 'main'
env:
    path_to_document: 'latex/main.tex'
jobs:
    build:
        if: contains(github.event.pull_request.head.ref, 'latex/**')
        name: Build LaTeX Document
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Github Action for LaTeX
              uses: xu-cheng/latex-action@3.2.0
              with:
                root_file: ${{env.path_to_document}}